version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-db:/data/db
    ports:
      - 27017:27017
    networks:
      - backend1

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo-db:27017
    depends_on:
      - mongodb
    networks:
      - frontend1
      - backend1

volumes:
  mongo-db:

networks:
  backend1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/16
  frontend1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16